// import React from "react";
// import { View, Text, Image, ScrollView, TouchableOpacity,StyleSheet } from "react-native";
// import { SafeAreaView } from "react-native-safe-area-context";
// import Icon from "react-native-vector-icons/Ionicons";
// import { router } from "expo-router";

import React, { useState, useEffect, useRef, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  TouchableOpacity,
  FlatList,
  Image,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
  ScrollView,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import withErrorBoundary from "../../components/ErrorBoundary";
import useUserDataStore from '../../src/store/userData';

const predefinedResponses = {
  "price": "The price of Product X is $50.",
  "support": "Please contact our support team at support@ecommerce.com for assistance.",
  "return": "To initiate a return, please go to your order history and select the item you wish to return.",
  "default": "Sorry, I didn't understand that. Could you please rephrase?",
  "track order": "Your order is in transit and will arrive soon.",
  "cancel order": "Your order cancellation request has been received.",
  "change address": "Please provide the new address to proceed with the change.",
  "return item": "Please select the item you'd like to return."
};

const quickReplies = ["Price", "Order Status", "Return", "Support"];

const AutoGeneratedChat = ({ username = "User" }) => {
  const [messages, setMessages] = useState([{ text: `Hi ${username}! How can I help you today?`, sender: 'bot' }]);
  const [userInput, setUserInput] = useState('');
  const [dynamicOptions, setDynamicOptions] = useState([]); 
  const userId = useUserDataStore((state) => state.users[0]?.id); 
  const router = useRouter();

  useEffect(() => {
    if (!userId) {
      router.push("/sign-in");
    }
  }, [userId]);

  const handleSendMessage = () => {
    if (userInput.trim()) {
      addMessage(userInput, 'user');
      setUserInput('');
      setTimeout(() => generateAndAddResponse(userInput.toLowerCase()), 300);
    }
  };

  const handleQuickReply = (reply) => {
    addMessage(reply, 'user');
    setTimeout(() => generateAndAddResponse(reply.toLowerCase()), 300);
  };

  const handleOrderOption = (option) => {
    const response = predefinedResponses[option.toLowerCase()] || predefinedResponses["default"];
    addMessage(response, 'bot');
    setDynamicOptions([]); 
  };

  const generateAndAddResponse = (input) => {
    if (input === "price") {
      addMessage(predefinedResponses["price"], 'bot');
      setDynamicOptions(["Product Price"]); 
    } else if (input === "order status") {
      addMessage(predefinedResponses["track order"], 'bot');
      setDynamicOptions(["Track Order", "Cancel Order", "Change Address"]); 
    } else if (input === "return") {
      addMessage(predefinedResponses["return item"], 'bot');
      setDynamicOptions(["Return Item"]); 
    } else if (input === "support") {
      addMessage(predefinedResponses["support"], 'bot');
      setDynamicOptions(["Contact Support"]); 
    } else {
      const botResponse = predefinedResponses[input] || predefinedResponses["default"];
      addMessage(botResponse, 'bot');
      setDynamicOptions([]); 
    }
  };

  const addMessage = (text, sender) => {
    setMessages((prevMessages) => [{ text, sender }, ...prevMessages]);
  };

  return (
    <View style={styles.container}>
      <FlatList
        data={messages}
        renderItem={({ item }) => (
          <View style={styles.messageContainer}>
            <Text style={item.sender === 'user' ? styles.userMessage : styles.botMessage}>
              {item.text}
            </Text>
          </View>
        )}
        keyExtractor={(item, index) => index.toString()}
        inverted
      />
      <View style={styles.quickRepliesContainer}>
        {quickReplies.map((reply, index) => (
          <TouchableOpacity key={index} style={styles.quickReplyButton} onPress={() => handleQuickReply(reply)}>
            <Text style={styles.quickReplyText}>{reply}</Text>
          </TouchableOpacity>
        ))}
      </View>
      {dynamicOptions.length > 0 && (
        <View style={styles.orderOptionsContainer}>
          <Text style={styles.orderOptionsText}>Choose an action:</Text>
          {dynamicOptions.map((option, index) => (
            <TouchableOpacity key={index} style={styles.orderOptionButton} onPress={() => handleOrderOption(option)}>
              <Text style={styles.orderOptionText}>{option}</Text>
            </TouchableOpacity>
          ))}
        </View>
      )}
      <TextInput
        style={styles.input}
        value={userInput}
        onChangeText={setUserInput}
        placeholder="Type a message..."
        placeholderTextColor="#8FFA09"
      />
      <Button title="Send" onPress={handleSendMessage} color="#8FFA09" />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: '#000000',
    justifyContent: 'flex-end',
    paddingBottom:80
  },
  messageContainer: {
    marginBottom: 10,
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#8FFA09',
    padding: 10,
    borderRadius: 10,
    color: '#000',
  },
  botMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#333333',
    padding: 10,
    borderRadius: 10,
    color: '#fff',
  },
  quickRepliesContainer: {
    flexDirection: 'row',
    marginBottom: 10,
    justifyContent: 'center',
  },
  quickReplyButton: {
    backgroundColor: '#333333',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    margin: 5,
  },
  quickReplyText: {
    color: '#8FFA09',
    fontWeight: 'bold',
  },
  orderOptionsContainer: {
    backgroundColor: '#222222',
    padding: 10,
    borderRadius: 10,
    marginVertical: 10,
  },
  orderOptionsText: {
    color: '#8FFA09',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 5,
  },
  orderOptionButton: {
    backgroundColor: '#555555',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    margin: 5,
  },
  orderOptionText: {
    color: '#8FFA09',
    fontWeight: 'bold',
  },
  input: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    color: '#8FFA09',
    borderColor: '#8FFA09',
  },
});

export default withErrorBoundary(AutoGeneratedChat);